# I2C
CONFIG_I2C=y

# Floating point
CONFIG_FPU=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Logging
CONFIG_LOG=y

# USB Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y

# ADC Support
CONFIG_ADC=y
CONFIG_ADC_ADS1115=y